"""empty message

Revision ID: bea561c229bd
Revises: 
Create Date: 2020-05-30 08:29:24.592626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea561c229bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Admin_email'), 'Admin', ['email'], unique=False)
    op.create_index(op.f('ix_Admin_username'), 'Admin', ['username'], unique=False)
    op.create_table('ReservMateriel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filiere', sa.Text(), nullable=True),
    sa.Column('matiere', sa.Text(), nullable=True),
    sa.Column('h_debut', sa.Text(), nullable=True),
    sa.Column('h_fin', sa.Text(), nullable=True),
    sa.Column('jour', sa.Text(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.Column('salle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReservSalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filiere', sa.Text(), nullable=True),
    sa.Column('matiere', sa.Text(), nullable=True),
    sa.Column('h_debut', sa.Text(), nullable=True),
    sa.Column('h_fin', sa.Text(), nullable=True),
    sa.Column('jour', sa.Text(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserv_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('filiere', sa.Text(), nullable=True),
    sa.Column('matiere', sa.Text(), nullable=True),
    sa.Column('h_debut', sa.DateTime(), nullable=True),
    sa.Column('h_fin', sa.DateTime(), nullable=True),
    sa.Column('jour', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historiqueMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('uniq_id', sa.Text(), nullable=True),
    sa.Column('info1', sa.Text(), nullable=True),
    sa.Column('info2', sa.Text(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiqueMS_id'), 'historiqueMS', ['id'], unique=True)
    op.create_index(op.f('ix_historiqueMS_type'), 'historiqueMS', ['type'], unique=False)
    op.create_table('Materiel',
    sa.Column('sn', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('exigence', sa.Text(), nullable=True),
    sa.Column('reserv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reserv_id'], ['ReservMateriel.id'], ),
    sa.PrimaryKeyConstraint('sn')
    )
    op.create_index(op.f('ix_Materiel_model'), 'Materiel', ['model'], unique=False)
    op.create_index(op.f('ix_Materiel_sn'), 'Materiel', ['sn'], unique=True)
    op.create_index(op.f('ix_Materiel_type'), 'Materiel', ['type'], unique=False)
    op.create_table('Salle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('nbre_place', sa.Integer(), nullable=True),
    sa.Column('reserv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reserv_id'], ['ReservSalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Salle_id'), 'Salle', ['id'], unique=True)
    op.create_index(op.f('ix_Salle_type'), 'Salle', ['type'], unique=False)
    op.create_table('User',
    sa.Column('matricule', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('poste', sa.Text(), nullable=True),
    sa.Column('reservMat_id', sa.Text(), nullable=True),
    sa.Column('reservSal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservMat_id'], ['ReservMateriel.id'], ),
    sa.ForeignKeyConstraint(['reservSal_id'], ['ReservSalle.id'], ),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Salle_type'), table_name='Salle')
    op.drop_index(op.f('ix_Salle_id'), table_name='Salle')
    op.drop_table('Salle')
    op.drop_index(op.f('ix_Materiel_type'), table_name='Materiel')
    op.drop_index(op.f('ix_Materiel_sn'), table_name='Materiel')
    op.drop_index(op.f('ix_Materiel_model'), table_name='Materiel')
    op.drop_table('Materiel')
    op.drop_index(op.f('ix_historiqueMS_type'), table_name='historiqueMS')
    op.drop_index(op.f('ix_historiqueMS_id'), table_name='historiqueMS')
    op.drop_table('historiqueMS')
    op.drop_table('historique')
    op.drop_table('ReservSalle')
    op.drop_table('ReservMateriel')
    op.drop_index(op.f('ix_Admin_username'), table_name='Admin')
    op.drop_index(op.f('ix_Admin_email'), table_name='Admin')
    op.drop_table('Admin')
    # ### end Alembic commands ###
